// export const API_ROOT = 'http://localhost:8080'
export const API_ROOT = 'https://cake-riverdev-web.herokuapp.com'
export const IS_SHOW = 'IS_SHOW'
export const GET_ALL_CATEGORIES = 'GET_ALL-CATEGORIES'
export const GET_CATEGORY_CAKES = 'GET_CATEGORY_CAKES'
export const GET_DETAILED_CAKE = 'GET_DETAILED_CAKE'
export const GET_CAKES = 'GET_CAKES'